(* open SQCaml *)
(**)
(* module To_test = struct *)
(*   let run_interpreter expected v = *)
(*     Alcotest.(check string) "Interpreter test" expected v *)
(* end *)
(**)
(* let () = *)
(*   Alcotest.run "Table Tests" *)
(*     [ (* ( "parsing-tests", *) *)
(*       (*   [ *) *)
(*       (*     Alcotest.test_case "Check parsed int" `Quick test_parsed_int; *) *)
(*       (*     Alcotest.test_case "Check parsed Meta_Command" `Quick *) *)
(*       (*       test_parsed_meta_command; *) *)
(*       (*     Alcotest.test_case "Check parsed Command" `Quick test_parsed_command; *) *)
(*       (*   ] ); *) ] *)
